---
title: "GENIE BPC Prostate Cancer - Landscape Report"
author: "Alex Paynter"
date: "4/4/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, include = F,
                      warning = F, message = F)
```

```{r}
library(readr)
library(here)
library(dplyr)
library(purrr)
library(rlang)
library(magrittr)

library(gt)
library(gtsummary)

as_list(here("R", dir(here("R"))))

# Source everything in the "R" folder - just functions, no scripts.
purrr::walk(.x = here("R", dir(here("R"))), .f = source)
```


```{r, warning = T}
read_wrap <- function(p) {
  read_csv(file = here("data-raw", p), show_col_types = F)
}

dft_pt <- read_wrap("patient_level_dataset.csv")
dft_ca_ind <- read_wrap("cancer_level_dataset_index.csv")

# A few sanity checks on the data:
if ((dft_pt$record_id %>% duplicated %>% any)) {
  stop("Duplicated records in patient level dataset.")
}

if (any(dft_pt$naaccr_sex_code != "Male")) {
  warning("Non-male sex detected for at least one participant (unexpectedly for Prostate cancer)")
}

```


```{r, demo_data_manipulation, include = F}
dft_pt_demo_sub <- dft_pt %>%
  mutate(
    `Race (primary)` = format_ptlevel_naaccr_race_code_primary(
      naaccr_race_code_primary
    ),
    `Ethnicity` = format_ptlevel_naaccr_ethnicity_code(
      naaccr_ethnicity_code
    )) %>%
  select(record_id, 
         Institution = institution,
         `Race (primary)`,
         `Ethnicity`)


dft_ca_ind_demo_sub <- dft_ca_ind %>%
  mutate(
    ca_dx_how = format_ca_dx_how(ca_dx_how),
    ca_hist_adeno_squamous = format_ca_hist_adeno_squamous(ca_hist_adeno_squamous),
    stage_dx = format_stage_dx(stage_dx),
    ca_path_n_stage = format_ca_path_n_stage(ca_path_n_stage)
  ) %>%
  select(
    record_id,
    `Age at dx (years)` = dob_ca_dx_yrs,
    `Stage at dx` = stage_dx,
    `Source of dx` = ca_dx_how,
    `Histology` = ca_hist_adeno_squamous, # at dx?
    `Pathologic N Stage` = ca_path_n_stage # describes spread to lymph nodes
  ) 


dft_demo <- full_join(dft_pt_demo_sub,
          dft_ca_ind_demo_sub,
          by = "record_id") 

```

### Table R1.1a: Baseline characteristics

```{r, tab_r1_1a, include = T}
dft_demo %>%
  select(-record_id) %>%
  gtsummary::tbl_summary(data = .)
```

### Table R1.1b: Baseline characteristics by site

```{r, tab_r1_1b, include = T}
dft_demo %>%
  select(-record_id) %>%
  gtsummary::tbl_summary(data = ., by = Institution)
```



