---
title: "BPC Prostate - Genomic"
author: "Alex Paynter"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, include = F,
                      warning = F, message = F,
                      fig.width = 7, fig.height = 5)
k_dpi <- 150
```

<style type="text/css">
.main-container {
  max-width: 1000px !important;
  margin: auto;
}
</style>

```{r}
library(purrr)
library(here)
library(fs)

purrr::walk(.x = fs::dir_ls(here('R')), .f = source) # also loads lots of packages.
```



```{r, set_gtsummary_theme}
theme_gtsummary_compact()
theme_gtsummary_language("en", big.mark = "") # for now.
```


```{r, warning = T}
read_wrap_clin <- function(p) {
  read_rds(file = here("data", 'clin', p))
}

dft_pt <- read_wrap_clin("dft_pt.rds")
dft_ca_ind <- read_wrap_clin("dft_ca_ind.rds")
dft_cpt <- read_wrap_clin("dft_cpt.rds")

read_wrap_geno <- function(p) {
  read_rds(file = here("data", 'genomic', p))
}

dft_gp_all <- read_wrap_geno('gene_panel_all.rds')
dft_gp_sum <- read_wrap_geno('gene_panel_sum.rds')
dft_gp_by_gene <- read_wrap_geno('gene_panel_by_gene.rds')

```


```{r}
# Add the number of patients and samples in parens:
dft_gp_all %<>%
  arrange(cpt_seq_assay_id) %>%
  left_join(
    ., 
    select(dft_gp_sum, cpt_seq_assay_id, n_pts, n_samples, n_genes),
    by = "cpt_seq_assay_id"
  ) %>%
  mutate(
    assay_lab = glue("{cpt_seq_assay_id} [{n_genes}] ({n_pts}, {n_samples})"),
    assay_lab = forcats::fct_inorder(assay_lab)
  ) %>%
  select(-n_pts, -n_samples, -n_genes)
  

gg_panel_coverage <- ggplot(
  data = dft_gp_all,
  aes(x = hugo, y = assay_lab)
) + 
  geom_raster() +
  theme_classic() + 
  scale_y_discrete(limits = rev) + 
  labs(x = "Gene (one line per gene)",
       title = "Gene panel coverage",
       subtitle = "Panels annotated with [number of genes] and (patients, samples) tested.") + 
  theme(
    axis.title.y = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.line.x = element_blank(),
    plot.title.position = "plot"
  )
```

## Content

### R2.1 Panel coverage

The following figures shows the coverage of

```{r, include = T, fig.width = 10, fig.height = 5}
gg_panel_coverage
```



